### ISSUE TITLE
Auto-casting of DBFields

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#24]
Follow up from https://github.com/silverstripe/silverstripe-search-service/issues/3. At the moment you have to be quite explicit with field types and casting. Those are implementation specific (e.g. Algolia wants dates as a timestamp, Elastic as RFC3339).

```yml
SilverStripe\SearchService\Service\IndexConfiguration:
  indexes:
    ingo:
      includeClasses:
        Page:
          fields:
            created:
              property: Created
              options:
                type: date
```

I think this should be handled transparently in `IndexingInterface->configure()` (for schema definitions) and `IndexingInterface->addDocument()` (for indexing). Or rather, `DataObjectDocument->toArray()` for casting, since the indexing interface is agnostic of DataObject/ORM concerns.

Types should stay configurable like in the example above, and the casting (e.g. to timestamp or RFC date) should be based on this.
