### ISSUE TITLE
Multiple Indexes and how to divide and define them

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-search-service#46]
After working with the `query_suggestion` endpoint today I realised that [you can't filter when making the request](https://discuss.elastic.co/t/add-a-filter-to-query-suggestion/258932). This causes a massive problem for the subsites implementation that we were looking at; that is, storing `subsite_id` and using that filter search requests. It means that a user will get suggestions based on the content of all subsites, which may return 0 results, even if they use the top suggestion.

Elastic's recommended solution is to [do a shallow search instead](https://discuss.elastic.co/t/how-to-add-filter-in-query-suggestion-feature/216112/2?u=andante), which has its own complications, and doesn't really return the same kind of data without some manipulation on our end.

The other alternative is to use a separate index for each subsite. Currently the only way to "divide" an index is to have different classes/fields in it, so I'd propose something along the lines of (h/t @madmatt) 

```yaml
indexes:
  content-main-pages:
    subsite_id: 0
    includeClasses:
      SiteTree:
        fields:
          title: true
  content-main-docs:
    subsite_id: 0
    includeClasses:
      Document:
        fields:
          title: true
  content-subsite1:
    subsite_id: 1
    copy-from:
      - content-main-pages
      - content-main-docs
  content-subsite2:
    subsite_id: 2
    copy_from: 
      - content-main
    includeClasses:    
      SiteTree:
        fields:
          content: true
```
Where you can inherit the config from other indexes - basically to reduce the need for endless copy-paste, but also add more fields if required.

Alternatively, we could add a filters param:

```yaml
indexes:
  content-main:
    filters:
      - property: SubsiteID
        value: 0
    includeClasses:
      SiteTree:
        fields:
          title: true
```

That is invoked in the `ShouldIndex()` method, or earlier.

Obviously this requires some more consideration in terms of how a reindex works, how individual model publishes work, and how credentials might work (do we then need separate credentials for each index?)

The question is ultimately, do we think a refactor of this nature is beneficial, or the best way forward, or should we look instead at implementing our own version of the suggestions API via a specific search?

All ideas welcomed 😄
